%% Fig. 7
% Remaining industrial emissions, terrestrial ecosystem sink benchmark,
% and emission-to-sink pressure-ratio sensitivity

clear;
clc;
close all;

%% =========================================================
% 1. Data
% ==========================================================

regions = {'BTH', 'YRD', 'PRD', 'CP'};

sectorNames = { ...
    'Iron and steel', ...
    'Cement', ...
    'Chemicals', ...
    'Non-ferrous metals', ...
    'Pulp and paper', ...
    'Equipment manuf.', ...
    'Other industry'};

% 2060 remaining industrial emissions under DMS
% Unit: Mt CO2 yr^-1
% Rows: BTH, YRD, PRD, CP
% Columns correspond to sectorNames
sectorResidual = [
    27.4440,  6.7266,  20.3797, 0.0840, 0.0633, 0.3717, 1.1137;
    16.1229, 11.1781, 142.6535, 0.2674, 1.2670, 3.2116, 1.2480;
     0.0715,  2.5326,  29.2763, 0.0402, 0.3040, 0.0554, 0.2238;
    20.0079,  7.8669,  22.4655, 2.4029, 0.1792, 0.0172, 4.1233
];

% Exact regional totals
exactRemaining = sum(sectorResidual, 2)';

% Rounded values reported in the manuscript
reportedRemaining = [56, 176, 33, 57];

% 2001–2020 terrestrial ecosystem sink benchmark
% Unit: Mt CO2 yr^-1
sinkBenchmark = [128.02, 148.77, 32.59, 210.69];

% Alternative sink benchmark conditions
sinkScale = [0.8, 1.0, 1.2];

% Pressure ratios
pressureRatio = bsxfun( ...
    @rdivide, ...
    reportedRemaining(:), ...
    sinkBenchmark(:) * sinkScale);

% Baseline pressure ratios under the 100% condition
baselineValues = pressureRatio(:, 2);

%% =========================================================
% 2. Colors
% ==========================================================

% Soft sector colors for panel (a)
sectorColors = [
    0.58, 0.70, 0.88;   % Iron and steel
    0.96, 0.76, 0.54;   % Cement
    0.88, 0.54, 0.63;   % Chemicals
    0.55, 0.78, 0.72;   % Non-ferrous metals
    0.73, 0.83, 0.55;   % Pulp and paper
    0.70, 0.72, 0.88;   % Equipment manufacturing
    0.84, 0.72, 0.57    % Other industry
];

% Regional colors for panel (b)
regionColors = [
    0.0000, 0.4470, 0.7410;   % BTH
    0.8500, 0.3250, 0.0980;   % YRD
    0.4660, 0.6740, 0.1880;   % PRD
    0.4940, 0.1840, 0.5560    % CP
];

regionMarkers = {'o', 's', '^', 'd'};

% Sink benchmark style
sinkFaceColor = [0.96, 0.91, 0.78];
sinkEdgeColor = [0.55, 0.41, 0.20];

% Light regional colors for baseline bars
lightRegionColors = ...
    0.42 .* regionColors + 0.58 .* ones(size(regionColors));

% Light-blue shading above pressure ratio = 1
shadeColor = [0.91, 0.96, 1.00];

%% =========================================================
% 3. Figure layout
% ==========================================================

fig = figure( ...
    'Color', 'w', ...
    'Units', 'pixels', ...
    'Position', [60, 60, 1600, 760], ...
    'Renderer', 'painters');

axA = axes( ...
    'Parent', fig, ...
    'Units', 'normalized', ...
    'Position', [0.065, 0.285, 0.405, 0.605]);

axB = axes( ...
    'Parent', fig, ...
    'Units', 'normalized', ...
    'Position', [0.545, 0.285, 0.395, 0.605]);

%% =========================================================
% 4. Panel (a)
% ==========================================================

hold(axA, 'on');

xGroup = 1:4;

xEmission = xGroup - 0.14;
xSink = xGroup + 0.24;

% Stacked remaining-emission bars
bEmission = bar( ...
    axA, ...
    xEmission, ...
    sectorResidual, ...
    0.54, ...
    'stacked', ...
    'EdgeColor', 'none');

for j = 1:numel(bEmission)
    bEmission(j).FaceColor = sectorColors(j, :);
end

% Terrestrial sink benchmark bars
bSink = bar( ...
    axA, ...
    xSink, ...
    sinkBenchmark, ...
    0.22, ...
    'FaceColor', sinkFaceColor, ...
    'EdgeColor', sinkEdgeColor, ...
    'LineWidth', 1.7);

%% Total-value labels
for i = 1:4

    text( ...
        axA, ...
        xEmission(i), ...
        exactRemaining(i) + 5.5, ...
        sprintf('%.0f', reportedRemaining(i)), ...
        'FontName', 'Arial', ...
        'FontSize', 13.5, ...
        'FontWeight', 'bold', ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'bottom', ...
        'Color', [0.08, 0.08, 0.08]);

    text( ...
        axA, ...
        xSink(i), ...
        sinkBenchmark(i) + 5.5, ...
        sprintf('%.2f', sinkBenchmark(i)), ...
        'FontName', 'Arial', ...
        'FontSize', 12.5, ...
        'FontWeight', 'bold', ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'bottom', ...
        'Color', sinkEdgeColor);
end

%% Chemical shares
chemicalShare = sectorResidual(:, 3)' ./ exactRemaining .* 100;
chemicalBottom = sum(sectorResidual(:, 1:2), 2)';

for i = 1:4
    chemicalMid = chemicalBottom(i) + sectorResidual(i, 3) / 2;

    text( ...
        axA, ...
        xEmission(i), ...
        chemicalMid, ...
        sprintf('%.0f%%', chemicalShare(i)), ...
        'FontName', 'Arial', ...
        'FontSize', 11.5, ...
        'FontWeight', 'bold', ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', ...
        'Color', [0.28, 0.08, 0.14]);
end

%% Axes
xlabel( ...
    axA, ...
    'Urban agglomeration', ...
    'FontName', 'Arial', ...
    'FontSize', 15);

ylabel( ...
    axA, ...
    'CO_2 emissions or sink benchmark (Mt CO_2 yr^{-1})', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'Interpreter', 'tex');

xlim(axA, [0.45, 4.55]);
ylim(axA, [0, 240]);

xticks(axA, xGroup);
xticklabels(axA, regions);

yticks(axA, 0:40:240);

%% Panel (a) legend
lgdA = legend( ...
    axA, ...
    [bEmission(:); bSink], ...
    [sectorNames, {'Terrestrial sink benchmark'}], ...
    'Orientation', 'horizontal', ...
    'NumColumns', 4, ...
    'Box', 'off', ...
    'FontName', 'Arial', ...
    'FontSize', 10.5);

%% =========================================================
% 5. Panel (b)
% ==========================================================

hold(axB, 'on');

% True x positions for 80%, 100%, and 120%
xSensitivity = [1, 2, 3];

% Light-blue region above pressure ratio = 1
patch( ...
    axB, ...
    [0.60, 3.10, 3.10, 0.60], ...
    [1.00, 1.00, 1.60, 1.60], ...
    shadeColor, ...
    'EdgeColor', 'none', ...
    'HandleVisibility', 'off');

%% Baseline bars
% Four city-group bars evenly distributed across the full panel
barX = [0.82, 1.54, 2.26, 2.98];
barWidth = 0.18;

barHandles = gobjects(4, 1);

for i = 1:4
    barHandles(i) = bar( ...
        axB, ...
        barX(i), ...
        baselineValues(i), ...
        barWidth, ...
        'FaceColor', lightRegionColors(i, :), ...
        'EdgeColor', regionColors(i, :), ...
        'LineWidth', 1.5);
end

%% Sensitivity lines
hRegion = gobjects(4, 1);

for i = 1:4
    hRegion(i) = plot( ...
        axB, ...
        xSensitivity, ...
        pressureRatio(i, :), ...
        '-', ...
        'Color', regionColors(i, :), ...
        'LineWidth', 2.8, ...
        'Marker', regionMarkers{i}, ...
        'MarkerSize', 9, ...
        'MarkerFaceColor', regionColors(i, :), ...
        'MarkerEdgeColor', regionColors(i, :));
end

%% Reference line at pressure ratio = 1
yline( ...
    axB, ...
    1, ...
    '--', ...
    'Color', [0.28, 0.38, 0.48], ...
    'LineWidth', 1.8, ...
    'HandleVisibility', 'off');

%% Baseline-value labels
for i = 1:4
    text( ...
        axB, ...
        barX(i), ...
        baselineValues(i) + 0.035, ...
        sprintf('%.2f', baselineValues(i)), ...
        'FontName', 'Arial', ...
        'FontSize', 12, ...
        'FontWeight', 'bold', ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'bottom', ...
        'Color', regionColors(i, :));
end

%% Region labels inside bars
for i = 1:4
    text( ...
        axB, ...
        barX(i), ...
        0.040, ...
        regions{i}, ...
        'FontName', 'Arial', ...
        'FontSize', 13.5, ...
        'FontWeight', 'normal', ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'bottom', ...
        'Color', [0.08, 0.08, 0.08]);
end

%% Axes
xlabel( ...
    axB, ...
    'Assumed terrestrial sink benchmark (% of baseline)', ...
    'FontName', 'Arial', ...
    'FontSize', 15);

ylabel( ...
    axB, ...
    'Emission-to-sink pressure ratio', ...
    'FontName', 'Arial', ...
    'FontSize', 15);

xlim(axB, [0.60, 3.10]);
ylim(axB, [0, 1.60]);

xticks(axB, xSensitivity);
xticklabels(axB, {'80%', '100%', '120%'});

yticks(axB, 0:0.2:1.6);

%% Panel (b) legend
lgdB = legend( ...
    axB, ...
    hRegion, ...
    regions, ...
    'Orientation', 'horizontal', ...
    'NumColumns', 4, ...
    'Box', 'off', ...
    'FontName', 'Arial', ...
    'FontSize', 12);

%% =========================================================
% 6. Common axis style
% ==========================================================

axesList = [axA, axB];

for k = 1:numel(axesList)
    ax = axesList(k);

    set(ax, ...
        'FontName', 'Arial', ...
        'FontSize', 13.5, ...
        'FontWeight', 'normal', ...
        'LineWidth', 1.5, ...
        'Box', 'on', ...
        'TickDir', 'in', ...
        'TickLength', [0.014, 0.014], ...
        'Layer', 'top', ...
        'Color', 'w', ...
        'XColor', [0.08, 0.08, 0.08], ...
        'YColor', [0.08, 0.08, 0.08], ...
        'GridColor', [0.60, 0.60, 0.60], ...
        'GridAlpha', 0.13, ...
        'XMinorTick', 'off', ...
        'YMinorTick', 'off');

    grid(ax, 'on');
end

%% =========================================================
% 7. Fixed legend positions
% ==========================================================

drawnow;

posA = axA.Position;
posB = axB.Position;

% Left legend
lgdA.Units = 'normalized';
leftLegendWidth = 0.405;
leftLegendHeight = 0.085;
leftLegendX = posA(1) + (posA(3) - leftLegendWidth) / 2;
leftLegendY = 0.112;

lgdA.Position = [ ...
    leftLegendX, ...
    leftLegendY, ...
    leftLegendWidth, ...
    leftLegendHeight];

% Right legend
lgdB.Units = 'normalized';
rightLegendWidth = 0.255;
rightLegendHeight = 0.040;
rightLegendX = posB(1) + (posB(3) - rightLegendWidth) / 2;
rightLegendY = 0.168;

lgdB.Position = [ ...
    rightLegendX, ...
    rightLegendY, ...
    rightLegendWidth, ...
    rightLegendHeight];

%% =========================================================
% 8. Panel labels
% ==========================================================

annotation( ...
    fig, ...
    'textbox', ...
    [posA(1)-0.040, posA(2)+posA(4)+0.003, 0.050, 0.045], ...
    'String', '(a)', ...
    'FontName', 'Arial', ...
    'FontSize', 17, ...
    'FontWeight', 'bold', ...
    'LineStyle', 'none', ...
    'HorizontalAlignment', 'left', ...
    'VerticalAlignment', 'middle', ...
    'Margin', 0);

annotation( ...
    fig, ...
    'textbox', ...
    [posB(1)-0.040, posB(2)+posB(4)+0.003, 0.050, 0.045], ...
    'String', '(b)', ...
    'FontName', 'Arial', ...
    'FontSize', 17, ...
    'FontWeight', 'bold', ...
    'LineStyle', 'none', ...
    'HorizontalAlignment', 'left', ...
    'VerticalAlignment', 'middle', ...
    'Margin', 0);

%% =========================================================
% 9. Export
% ==========================================================

exportgraphics( ...
    fig, ...
    'Fig7_emission_sink_pressure_final.png', ...
    'Resolution', 600);

exportgraphics( ...
    fig, ...
    'Fig7_emission_sink_pressure_final.pdf', ...
    'ContentType', 'vector');
