%% Fig. S1
% Sensitivity of the terrestrial ecosystem carbon sink benchmark and
% industrial emission pressure ratio to the temporal completeness threshold.
% Data are written directly in this script and match Table S9, Panel A.

clear;
clc;
close all;

%% Data
regions = {'BTH', 'YRD', 'PRD', 'CP'};
thresholds = [5, 10, 15];

sinkValues = [
    128.431579, 128.019207, 127.137954;
    152.332867, 148.765324, 134.528297;
     40.232474,  32.594748,  15.095673;
    212.578148, 210.686456, 151.417489
];

remainingEmissions = [56, 176, 33, 57]';
pressureRatio = remainingEmissions ./ sinkValues;

regionColors = [
    0.0000, 0.4470, 0.7410;
    0.8500, 0.3250, 0.0980;
    0.4660, 0.6740, 0.1880;
    0.4940, 0.1840, 0.5560
];

regionMarkers = {'o', 's', '^', 'd'};

%% Figure
fig = figure( ...
    'Color', 'w', ...
    'Units', 'pixels', ...
    'Position', [80, 80, 1320, 560], ...
    'Renderer', 'painters');

axA = axes( ...
    'Parent', fig, ...
    'Units', 'normalized', ...
    'Position', [0.085, 0.20, 0.37, 0.70]);

axB = axes( ...
    'Parent', fig, ...
    'Units', 'normalized', ...
    'Position', [0.575, 0.20, 0.37, 0.70]);

%% Panel (a)
hold(axA, 'on');

h = gobjects(4,1);

for i = 1:4
    h(i) = plot( ...
        axA, ...
        thresholds, ...
        sinkValues(i,:), ...
        '-', ...
        'Color', regionColors(i,:), ...
        'LineWidth', 2.4, ...
        'Marker', regionMarkers{i}, ...
        'MarkerSize', 8, ...
        'MarkerFaceColor', regionColors(i,:), ...
        'MarkerEdgeColor', regionColors(i,:));
end

xlim(axA, [4, 16]);
ylim(axA, [0, 240]);
xticks(axA, thresholds);
yticks(axA, 0:40:240);

xlabel(axA, ...
    'Minimum valid observation years', ...
    'FontName', 'Arial', ...
    'FontSize', 14);

ylabel(axA, ...
    'Terrestrial sink benchmark (Mt CO_2 yr^{-1})', ...
    'FontName', 'Arial', ...
    'FontSize', 14, ...
    'Interpreter', 'tex');

%% Panel (b)
hold(axB, 'on');

for i = 1:4
    plot( ...
        axB, ...
        thresholds, ...
        pressureRatio(i,:), ...
        '-', ...
        'Color', regionColors(i,:), ...
        'LineWidth', 2.4, ...
        'Marker', regionMarkers{i}, ...
        'MarkerSize', 8, ...
        'MarkerFaceColor', regionColors(i,:), ...
        'MarkerEdgeColor', regionColors(i,:));
end

yline( ...
    axB, ...
    1, ...
    '--', ...
    'Color', [0.35, 0.35, 0.35], ...
    'LineWidth', 1.5, ...
    'HandleVisibility', 'off');

xlim(axB, [4, 16]);
ylim(axB, [0, 2.4]);
xticks(axB, thresholds);
yticks(axB, 0:0.4:2.4);

xlabel(axB, ...
    'Minimum valid observation years', ...
    'FontName', 'Arial', ...
    'FontSize', 14);

ylabel(axB, ...
    'Emission-to-sink pressure ratio', ...
    'FontName', 'Arial', ...
    'FontSize', 14);

%% Common style
axesList = [axA, axB];

for k = 1:numel(axesList)
    ax = axesList(k);

    set(ax, ...
        'FontName', 'Arial', ...
        'FontSize', 12.5, ...
        'LineWidth', 1.3, ...
        'Box', 'on', ...
        'TickDir', 'in', ...
        'TickLength', [0.014, 0.014], ...
        'Layer', 'top', ...
        'Color', 'w', ...
        'XColor', [0.08, 0.08, 0.08], ...
        'YColor', [0.08, 0.08, 0.08], ...
        'GridColor', [0.65, 0.65, 0.65], ...
        'GridAlpha', 0.12);

    grid(ax, 'on');
end

lgd = legend( ...
    axA, ...
    h, ...
    regions, ...
    'Orientation', 'horizontal', ...
    'NumColumns', 4, ...
    'Box', 'off', ...
    'FontName', 'Arial', ...
    'FontSize', 11);

lgd.Units = 'normalized';
lgd.Position = [0.385, 0.045, 0.24, 0.05];

annotation( ...
    fig, ...
    'textbox', ...
    [0.045, 0.90, 0.05, 0.05], ...
    'String', '(a)', ...
    'FontName', 'Arial', ...
    'FontSize', 16, ...
    'FontWeight', 'bold', ...
    'LineStyle', 'none', ...
    'Margin', 0);

annotation( ...
    fig, ...
    'textbox', ...
    [0.535, 0.90, 0.05, 0.05], ...
    'String', '(b)', ...
    'FontName', 'Arial', ...
    'FontSize', 16, ...
    'FontWeight', 'bold', ...
    'LineStyle', 'none', ...
    'Margin', 0);

%% Export
exportgraphics( ...
    fig, ...
    'FigS1_temporal_completeness_sensitivity.png', ...
    'Resolution', 600);

exportgraphics( ...
    fig, ...
    'FigS1_temporal_completeness_sensitivity.pdf', ...
    'ContentType', 'vector');
